### ISSUE TITLE
Need to modify method to work with Python 3.8 (and probably all Python3 versions under 3.9)

### ISSUE THREAD

**Issue by kiamatthews** [OlafHaalstra/log4jcheck#1]
Running this script with Python 3.8 produced the following error:
```
Traceback (most recent call last):
  File "log4check.py", line 15, in <module>
    def check_post_parameter(method: str, identifier: str, url: str, parameters: list[str], canarytoken: str):
TypeError: 'type' object is not subscriptable
```

Modifying line 15 to following fixed the issue:
`def check_post_parameter(method, identifier, url, parameters, canarytoken):`

(source: https://stackoverflow.com/a/63460173)

**Comment by OlafHaalstra** [comment]
Thanks for the issue, I resolved it by replacing `list[str]` by `list`.
