### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Pepsi-Guy** [OlafHaalstra/log4jcheck#2]
![image](https://user-images.githubusercontent.com/109484073/181666230-61035f07-0896-45a1-8fcd-19b7341957bb.png)

if we have the same result with a real target it's vulnerable ?

because i have src_data   {'log4_shell_computer_name':'hg1vds3dsv5g2bd1db5n52g'}

**Comment by Pepsi-Guy** [comment]
and  why we don't have the Hostname like hostName "target"

thank you !

**Comment by OlafHaalstra** [comment]
Hi @Pepsi-Guy 

This can be the case. Please refer to the logs in `./run/logs/[DATETIME].log` to see which request identifier matches with the url and method. This should give some indication which likely is the affected host.
